"use client";
import { useEffect,useState } from "react";
import { supabase } from "@/lib/supabase";
export default function AdminRules(){
 const [allowed,setAllowed]=useState(false),[loading,setLoading]=useState(true),[docs,setDocs]=useState<any[]>([]),[busy,setBusy]=useState(false),[msg,setMsg]=useState("");
 useEffect(()=>{(async()=>{const {data:{user}}=await supabase.auth.getUser();if(!user){setLoading(false);return}const {data:p}=await supabase.from("profiles").select("role").eq("id",user.id).single();if(!p||!["admin","owner","content_manager"].includes(p.role)){setLoading(false);return}setAllowed(true);load();setLoading(false)})()},[]);
 async function load(){const {data}=await supabase.from("rule_documents").select("*").order("created_at",{ascending:false});if(data)setDocs(data)}
 async function upload(file:File){if(file.type!=="application/pdf")return setMsg("اختر PDF فقط.");if(file.size>50*1024*1024)return setMsg("الحد الأقصى 50MB.");setBusy(true);const {data:{user}}=await supabase.auth.getUser();const safe=file.name.replace(/[^a-zA-Z0-9._-]/g,"_");const path=(user?.id||"admin")+"/"+Date.now()+"-"+safe;const up=await supabase.storage.from("sailing-rules").upload(path,file,{contentType:"application/pdf"});if(up.error){setMsg(up.error.message);setBusy(false);return}const {data,error}=await supabase.from("rule_documents").insert({title:file.name,file_path:path,mime_type:file.type,file_size:file.size,status:"uploaded",uploaded_by:user?.id}).select("*").single();if(error){setMsg(error.message);setBusy(false);return}setDocs(x=>[data,...x]);setMsg("تم رفع الوثيقة.");setBusy(false)}
 if(loading)return <div className="admin-loading">جارٍ التحقق…</div>;
 if(!allowed)return <div className="admin-denied" dir="rtl"><h1>غير مصرح</h1><a href="/admin">العودة</a></div>;
 return <main className="admin-shell" dir="rtl"><aside className="admin-sidebar"><div className="admin-brand"><div className="brand-mark">SA</div><div><strong>Sailing AI</strong><span>مكتبة القواعد</span></div></div><nav><a className="selected" href="/admin/rules">القواعد</a><a href="/admin/races">السباقات</a><a href="/admin/ai">AI Knowledge</a><a href="/admin">لوحة الإدارة</a></nav></aside><section className="admin-main"><header className="admin-header"><div><span className="eyebrow">RULES LIBRARY</span><h1>القواعد والقوانين</h1></div></header><div className="admin-content">{msg&&<div className="admin-alert">{msg}</div>}<div className="admin-card"><h2>رفع مستند رسمي</h2><p>ملفات PDF تحفظ في Bucket خاص ولا تصبح عامة.</p><label className="primary" style={{display:"inline-block",cursor:"pointer"}}>{busy?"جارٍ الرفع…":"اختيار PDF"}<input hidden type="file" accept="application/pdf" disabled={busy} onChange={e=>{const f=e.target.files?.[0];if(f)upload(f)}}/></label></div><div className="admin-card"><h2>المستندات</h2><div className="table-wrap"><table><thead><tr><th>الوثيقة</th><th>الإصدار</th><th>الحالة</th><th>التاريخ</th></tr></thead><tbody>{docs.map(d=><tr key={d.id}><td>{d.title}</td><td>{d.version||"—"}</td><td>{d.status}</td><td>{new Date(d.created_at).toLocaleDateString("ar-LY")}</td></tr>)}</tbody></table></div></div></div></section></main>
}