"use client";
import { useEffect,useState } from "react";
import { supabase } from "@/lib/supabase";
export default function AdminRaces(){
 const [allowed,setAllowed]=useState(false),[loading,setLoading]=useState(true),[races,setRaces]=useState<any[]>([]),[classes,setClasses]=useState<any[]>([]),[form,setForm]=useState({name:"",city:"",venue:"",start_date:"",rounds_count:"3",class_id:""}),[msg,setMsg]=useState("");
 useEffect(()=>{(async()=>{const {data:{user}}=await supabase.auth.getUser();if(!user){setLoading(false);return}const {data:p}=await supabase.from("profiles").select("role").eq("id",user.id).single();if(!p||!["admin","owner","race_manager"].includes(p.role)){setLoading(false);return}setAllowed(true);load();setLoading(false)})()},[]);
 async function load(){const [r,c]=await Promise.all([supabase.from("races").select("id,name,city,venue,start_date,status,rounds_count").order("start_date"),supabase.from("race_classes").select("id,name").eq("is_active",true).order("name")]);if(r.data)setRaces(r.data);if(c.data)setClasses(c.data)}
 async function create(){if(!form.name.trim())return setMsg("اسم السباق مطلوب.");const {data:{user}}=await supabase.auth.getUser();const {data,error}=await supabase.from("races").insert({name:form.name,city:form.city||null,venue:form.venue||null,start_date:form.start_date?new Date(form.start_date).toISOString():null,rounds_count:Number(form.rounds_count)||1,class_id:form.class_id||null,created_by:user?.id}).select("id,name,city,venue,start_date,status,rounds_count").single();if(error)return setMsg(error.message);if(data)setRaces(x=>[...x,data]);setForm({name:"",city:"",venue:"",start_date:"",rounds_count:"3",class_id:""});setMsg("تم إنشاء السباق.");}
 if(loading)return <div className="admin-loading">جارٍ التحقق…</div>;
 if(!allowed)return <div className="admin-denied" dir="rtl"><h1>غير مصرح</h1><a href="/admin">العودة</a></div>;
 return <main className="admin-shell" dir="rtl"><aside className="admin-sidebar"><div className="admin-brand"><div className="brand-mark">SA</div><div><strong>Sailing AI</strong><span>إدارة السباقات</span></div></div><nav><a className="selected" href="/admin/races">السباقات</a><a href="/admin/rules">القواعد</a><a href="/admin/ai">AI Knowledge</a><a href="/admin">لوحة الإدارة</a></nav></aside><section className="admin-main"><header className="admin-header"><div><span className="eyebrow">RACE CONTROL</span><h1>إدارة السباقات</h1></div></header><div className="admin-content">{msg&&<div className="admin-alert">{msg}</div>}<div className="admin-card"><h2>إنشاء سباق</h2><div className="form-grid"><label>اسم السباق<input value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/></label><label>الفئة<select value={form.class_id} onChange={e=>setForm({...form,class_id:e.target.value})}><option value="">اختر</option>{classes.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label><label>المدينة<input value={form.city} onChange={e=>setForm({...form,city:e.target.value})}/></label><label>المكان<input value={form.venue} onChange={e=>setForm({...form,venue:e.target.value})}/></label><label>البداية<input type="datetime-local" value={form.start_date} onChange={e=>setForm({...form,start_date:e.target.value})}/></label><label>الجولات<input type="number" min="1" value={form.rounds_count} onChange={e=>setForm({...form,rounds_count:e.target.value})}/></label></div><button className="primary" onClick={create}>إنشاء السباق</button></div><div className="admin-card"><h2>السباقات</h2><div className="table-wrap"><table><thead><tr><th>الاسم</th><th>المكان</th><th>البداية</th><th>الجولات</th><th>الحالة</th></tr></thead><tbody>{races.map(r=><tr key={r.id}><td>{r.name}</td><td>{r.city||"—"} {r.venue?"• "+r.venue:""}</td><td>{r.start_date?new Date(r.start_date).toLocaleString("ar-LY"):"—"}</td><td>{r.rounds_count}</td><td>{r.status}</td></tr>)}</tbody></table></div></div></div></section></main>
}