"use client";
import { useEffect,useState } from "react";
import { supabase } from "@/lib/supabase";
export default function AIKnowledge(){
 const [allowed,setAllowed]=useState(false),[loading,setLoading]=useState(true),[docs,setDocs]=useState<any[]>([]),[chunks,setChunks]=useState(0);
 useEffect(()=>{(async()=>{const {data:{user}}=await supabase.auth.getUser();if(!user){setLoading(false);return}const {data:p}=await supabase.from("profiles").select("role").eq("id",user.id).single();if(!p||!["admin","owner","content_manager"].includes(p.role)){setLoading(false);return}setAllowed(true);const [d,c]=await Promise.all([supabase.from("rule_documents").select("id,title,status,created_at").order("created_at",{ascending:false}),supabase.from("rule_chunks").select("id",{count:"exact",head:true})]);if(d.data)setDocs(d.data);setChunks(c.count||0);setLoading(false)})()},[]);
 if(loading)return <div className="admin-loading">جارٍ التحقق…</div>;
 if(!allowed)return <div className="admin-denied" dir="rtl"><h1>غير مصرح</h1><a href="/admin">العودة</a></div>;
 return <main className="admin-shell" dir="rtl"><aside className="admin-sidebar"><div className="admin-brand"><div className="brand-mark">SA</div><div><strong>Sailing AI</strong><span>AI Knowledge</span></div></div><nav><a className="selected" href="/admin/ai">AI Knowledge</a><a href="/admin/rules">القواعد</a><a href="/admin/races">السباقات</a><a href="/admin">لوحة الإدارة</a></nav></aside><section className="admin-main"><header className="admin-header"><div><span className="eyebrow">RAG • KNOWLEDGE</span><h1>قاعدة معرفة Sail AI</h1></div></header><div className="admin-content"><div className="stat-grid"><div className="stat"><span>المستندات</span><b>{docs.length}</b></div><div className="stat"><span>Chunks</span><b>{chunks}</b></div><div className="stat"><span>Vector</span><b>pgvector</b></div><div className="stat"><span>Embedding</span><b>1536</b></div></div><div className="admin-card"><h2>مسار المعرفة</h2><p>PDF → استخراج النص → تقسيم المحتوى → Embeddings → pgvector → استرجاع المصادر → Sail AI.</p></div><div className="admin-card"><h2>الوثائق</h2><div className="table-wrap"><table><thead><tr><th>الوثيقة</th><th>الحالة</th><th>التاريخ</th></tr></thead><tbody>{docs.map(d=><tr key={d.id}><td>{d.title}</td><td>{d.status}</td><td>{new Date(d.created_at).toLocaleDateString("ar-LY")}</td></tr>)}</tbody></table></div></div></div></section></main>
}